/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/blocklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Blocklist
         * @description List blocklist entries, optionally scoped to one media item.
         */
        get: operations["list_blocklist_api_v1_blocklist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blocklist/{blocklist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Blocklist
         * @description Remove a blocklist entry (operator un-blocklist).
         */
        delete: operations["delete_blocklist_api_v1_blocklist__blocklist_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/discover/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover Home
         * @description Return the server-composed Discover home (spotlight + ordered rows).
         */
        get: operations["discover_home_api_v1_discover_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/discover/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover Search
         * @description Search TMDB for movies / shows matching ``query`` (optional ``year``).
         */
        get: operations["discover_search_api_v1_discover_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/discover/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover Category
         * @description Return a paginated movie category (``trending`` / ``popular`` / ``upcoming``).
         */
        get: operations["discover_category_api_v1_discover__category__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quality-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quality Profile Endpoint
         * @description Return the alpha default quality profile (ordered low -> high, with cutoff).
         */
        get: operations["get_quality_profile_endpoint_api_v1_quality_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Queue
         * @description Return the live download queue (read-only).
         *
         *     Passive by design: the background reconcile loop is the single owner of
         *     cross-system truth, so a queue poll never reconciles — doing so could race the
         *     loop's importer CAS and clobber an ``importing`` claim. The loop refreshes
         *     frequently, so the persisted progress/status is fresh enough to display, and the
         *     queue stays viewable even while qBittorrent is unreachable.
         */
        get: operations["get_queue_api_v1_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/grab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grab Endpoint
         * @description Grab a release for a request: a chosen one, or the top accepted pick.
         */
        post: operations["grab_endpoint_api_v1_queue_grab_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/{download_id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Endpoint
         * @description Operator retry: (re)run the import for a download (e.g. an ImportBlocked row).
         *
         *     Requires Plex + the Movies root configured (409 ``service_not_configured``
         *     otherwise). The correction-without-a-terminal button for a blocked import.
         */
        post: operations["import_endpoint_api_v1_queue__download_id__import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/{download_id}/mark-failed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Failed Endpoint
         * @description Operator move: mark a download failed (optionally blocklisting the release).
         */
        post: operations["mark_failed_endpoint_api_v1_queue__download_id__mark_failed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Requests Endpoint
         * @description List all media requests.
         */
        get: operations["list_requests_endpoint_api_v1_requests_get"];
        put?: never;
        /**
         * Create Request Endpoint
         * @description Create a request (or return the existing active one for this media).
         *
         *     If Plex is configured and the movie is already in the library, the request is
         *     recorded directly as ``available`` (no needless search/grab).
         */
        post: operations["create_request_endpoint_api_v1_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Request Endpoint
         * @description Return a single media request, or 404.
         */
        get: operations["get_request_endpoint_api_v1_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Preview Endpoint
         * @description Run the decision engine over the indexer results for this media.
         */
        post: operations["search_preview_endpoint_api_v1_search_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings Endpoint
         * @description Return the redacted service config (secrets shown as ``"***"``).
         */
        get: operations["get_settings_endpoint_api_v1_settings_get"];
        /**
         * Put Settings Endpoint
         * @description Upsert the provided config and return the redacted result.
         *
         *     A secret field whose incoming value is the redaction mask (``"***"``) is a
         *     no-op: GET returns ``"***"`` for a configured secret, so a FE that round-trips
         *     the whole object back (e.g. after editing only ``plex_url``) must not clobber
         *     the real credential with the mask — a silent secret-wipe that would only
         *     surface later as an auth failure to the downstream service.
         */
        put: operations["put_settings_endpoint_api_v1_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/plex-libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plex Libraries Endpoint
         * @description Movie library folders Plex reports, for the Settings ``movies_root`` picker.
         *
         *     Uses the stored Plex creds (no re-typing the token); 409 if Plex is unconfigured.
         */
        get: operations["plex_libraries_endpoint_api_v1_settings_plex_libraries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete
         * @description Persist the validated creds, mint the app api key, mark initialized.
         *
         *     One-shot AND concurrency-safe: rejected with 409 once initialized. Two
         *     concurrent ``/complete`` calls can both pass an in-memory ``initialized`` check
         *     and double-write (a ``settings.key`` unique-constraint 500, or one overwriting
         *     the other's just-issued ``app_api_key``). To prevent that, initialization is
         *     claimed with a CONDITIONAL update (``... WHERE id = 1 AND initialized = false``):
         *     exactly one request flips the row, and the loser sees ``rowcount == 0`` and is
         *     rejected 409 — so only the winner mints the key and writes the creds. Re-running
         *     setup post-init would also let an unauthenticated caller overwrite every stored
         *     credential and re-disclose the app key, so post-init changes must go through the
         *     authenticated ``PUT /settings``.
         */
        post: operations["complete_api_v1_setup_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status
         * @description Report install state only — never the app api key.
         *
         *     The key is revealed exactly once, in the ``/complete`` response (the SPA
         *     persists it then). Re-serving it from this unauthenticated GET would hand any
         *     anonymous caller the master ``X-Api-Key`` post-init, nullifying the entire
         *     auth model, so ``app_api_key`` is always ``None`` here.
         */
        get: operations["status_api_v1_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/validate/plex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Plex Endpoint
         * @description Test candidate Plex credentials.
         */
        post: operations["validate_plex_endpoint_api_v1_setup_validate_plex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/validate/prowlarr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Prowlarr Endpoint
         * @description Test candidate Prowlarr credentials.
         */
        post: operations["validate_prowlarr_endpoint_api_v1_setup_validate_prowlarr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/validate/qbittorrent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Qbittorrent Endpoint
         * @description Test candidate qBittorrent credentials.
         */
        post: operations["validate_qbittorrent_endpoint_api_v1_setup_validate_qbittorrent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/validate/tmdb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Tmdb Endpoint
         * @description Test a candidate TMDB api key.
         */
        post: operations["validate_tmdb_endpoint_api_v1_setup_validate_tmdb_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe used by the container healthcheck and monitoring.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcceptedRelease
         * @description A release that passed the quality gate and blocklist, with its ranking.
         */
        AcceptedRelease: {
            /** Guid */
            guid: string;
            /** Indexer */
            indexer: string;
            /** Info Hash */
            info_hash?: string | null;
            /** Quality Name */
            quality_name: string;
            /** Resolution */
            resolution: string;
            /** Score */
            score: number;
            /** Seeders */
            seeders?: number | null;
            /** Source */
            source: string;
            /** Title */
            title: string;
        };
        /**
         * BlocklistEntry
         * @description A blocklist entry as returned to the client.
         */
        BlocklistEntry: {
            /** Added At */
            added_at?: string | null;
            /** Id */
            id: number;
            /** Indexer */
            indexer?: string | null;
            /** Media Type */
            media_type?: string | null;
            /** Protocol */
            protocol?: string | null;
            /** Reason */
            reason: string;
            /** Source Title */
            source_title: string;
            /** Tmdb Id */
            tmdb_id?: number | null;
            /** Torrent Hash */
            torrent_hash?: string | null;
        };
        /**
         * BlocklistResponse
         * @description A list of blocklist entries.
         */
        BlocklistResponse: {
            /** Entries */
            entries: components["schemas"]["BlocklistEntry"][];
        };
        /**
         * CreateRequestBody
         * @description Create a media request by tmdb id + media type.
         */
        CreateRequestBody: {
            /**
             * Media Type
             * @enum {string}
             */
            media_type: "movie" | "tv";
            /** Tmdb Id */
            tmdb_id: number;
        };
        /**
         * DiscoverHomeResponse
         * @description The composed Discover home: an optional spotlight + ordered rows.
         */
        DiscoverHomeResponse: {
            /** Rows */
            rows: components["schemas"]["DiscoverHomeRow"][];
            spotlight?: components["schemas"]["DiscoverResult"] | null;
        };
        /**
         * DiscoverHomeRow
         * @description One server-composed Discover row: a title + its items.
         *
         *     ``row_type`` is an OPEN string (e.g. ``trending`` / ``popular`` / ``upcoming``)
         *     so the frontend renders rows generically and stays dumb about WHY a row exists
         *     — TV and recommendation rows slot in later with no contract change.
         */
        DiscoverHomeRow: {
            /** Items */
            items: components["schemas"]["DiscoverResult"][];
            /** Row Type */
            row_type: string;
            /** Title */
            title: string;
        };
        /**
         * DiscoverListResponse
         * @description A paginated category listing (trending / popular / upcoming).
         */
        DiscoverListResponse: {
            /** Page */
            page: number;
            /** Results */
            results: components["schemas"]["DiscoverResult"][];
            /** Total Pages */
            total_pages: number;
            /** Total Results */
            total_results: number;
        };
        /**
         * DiscoverResult
         * @description One discovery search row.
         */
        DiscoverResult: {
            /** Backdrop Url */
            backdrop_url?: string | null;
            /**
             * Media Type
             * @enum {string}
             */
            media_type: "movie" | "tv";
            /** Overview */
            overview?: string | null;
            /** Poster Url */
            poster_url?: string | null;
            /** Title */
            title: string;
            /** Tmdb Id */
            tmdb_id: number;
            /** Year */
            year?: number | null;
        };
        /**
         * DiscoverSearchResponse
         * @description The discovery search result set.
         */
        DiscoverSearchResponse: {
            /** Results */
            results: components["schemas"]["DiscoverResult"][];
        };
        /**
         * GrabRequest
         * @description Grab a release for a request: a chosen ``info_hash``/``guid`` or the top pick.
         *
         *     With neither ``info_hash`` nor ``guid`` set, the highest-ranked accepted
         *     release is grabbed ("grab top"). For a TV request, ``season`` scopes both the
         *     indexer search and the stored download to that season; it is ignored for
         *     movies.
         */
        GrabRequest: {
            /** Guid */
            guid?: string | null;
            /** Info Hash */
            info_hash?: string | null;
            /** Request Id */
            request_id: number;
            /** Season */
            season?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PlexLibraryOption
         * @description One movie-library folder Plex reports, with whether the app can write to it.
         *
         *     ``path`` is a Plex library location (from Plex's own ``/library/sections``), so
         *     choosing it for ``movies_root`` avoids a typed path entirely (and the path↔
         *     section mismatch that breaks a targeted scan). ``writable`` is the app's own
         *     check (``None`` when not probed — see the field): a known-not-writable location
         *     is the split-mount signal — surfaced, not hidden.
         */
        PlexLibraryOption: {
            /** Path */
            path: string;
            /** Section Key */
            section_key: string;
            /** Title */
            title: string;
            /** Writable */
            writable?: boolean | null;
        };
        /**
         * PlexValidateRequest
         * @description Candidate Plex credentials to test (``POST /setup/validate/plex``).
         */
        PlexValidateRequest: {
            /** Token */
            token: string;
            /** Url */
            url: string;
        };
        /**
         * ProwlarrValidateRequest
         * @description Candidate Prowlarr credentials to test.
         */
        ProwlarrValidateRequest: {
            /** Api Key */
            api_key: string;
            /** Url */
            url: string;
        };
        /**
         * QbittorrentValidateRequest
         * @description Candidate qBittorrent credentials to test.
         */
        QbittorrentValidateRequest: {
            /** Password */
            password: string;
            /** Url */
            url: string;
            /** Username */
            username: string;
        };
        /**
         * QualityProfileItemResponse
         * @description One ordered entry in the quality profile.
         */
        QualityProfileItemResponse: {
            /** Allowed */
            allowed: boolean;
            /** Name */
            name: string;
            /** Quality Id */
            quality_id: number;
            /** Resolution */
            resolution: string;
            /** Source */
            source: string;
        };
        /**
         * QualityProfileResponse
         * @description The serialized default quality profile (ordered low -> high, with cutoff).
         */
        QualityProfileResponse: {
            /** Cutoff Name */
            cutoff_name: string;
            /** Cutoff Quality Id */
            cutoff_quality_id: number;
            /** Id */
            id: number;
            /** Items */
            items: components["schemas"]["QualityProfileItemResponse"][];
            /** Name */
            name: string;
            /** Upgrade Allowed */
            upgrade_allowed: boolean;
        };
        /**
         * QueueItem
         * @description A tracked download in the live queue.
         */
        QueueItem: {
            /** Failed Reason */
            failed_reason?: string | null;
            /** Id */
            id: number;
            /** Media Request Id */
            media_request_id?: number | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Seed Ratio
             * @default 0
             */
            seed_ratio: number;
            /** Status */
            status: string;
            /** Tmdb Id */
            tmdb_id?: number | null;
            /** Torrent Hash */
            torrent_hash: string;
        };
        /**
         * QueueResponse
         * @description The reconciled download queue.
         */
        QueueResponse: {
            /** Queue */
            queue: components["schemas"]["QueueItem"][];
        };
        /**
         * RejectedRelease
         * @description A discarded release paired with its surfaced rejection reason.
         */
        RejectedRelease: {
            /** Reason */
            reason: string;
            /** Title */
            title: string;
        };
        /**
         * RequestListResponse
         * @description A list of media requests.
         */
        RequestListResponse: {
            /** Requests */
            requests: components["schemas"]["RequestResponse"][];
        };
        /**
         * RequestResponse
         * @description A media request as returned to the client.
         */
        RequestResponse: {
            /** Backdrop Url */
            backdrop_url?: string | null;
            /** Id */
            id: number;
            /**
             * Is Anime
             * @default false
             */
            is_anime: boolean;
            /** Media Type */
            media_type: string;
            /** Poster Url */
            poster_url?: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Tmdb Id */
            tmdb_id: number;
            /** Year */
            year?: number | null;
        };
        /**
         * SearchPreviewRequest
         * @description Preview by ``request_id`` OR by an explicit media descriptor.
         *
         *     When ``request_id`` is set the other fields are ignored (resolved from the
         *     stored request). Otherwise ``tmdb_id``, ``media_type`` and ``title`` are
         *     required.
         */
        SearchPreviewRequest: {
            /** Media Type */
            media_type?: ("movie" | "tv") | null;
            /** Request Id */
            request_id?: number | null;
            /** Season */
            season?: number | null;
            /** Title */
            title?: string | null;
            /** Tmdb Id */
            tmdb_id?: number | null;
            /** Year */
            year?: number | null;
        };
        /**
         * SearchPreviewResponse
         * @description Ranked accepted releases, per-release rejections, and the empty-set flag.
         */
        SearchPreviewResponse: {
            /** Accepted */
            accepted: components["schemas"]["AcceptedRelease"][];
            /** No Acceptable Release */
            no_acceptable_release: boolean;
            /** Rejected */
            rejected: components["schemas"]["RejectedRelease"][];
        };
        /**
         * ServiceValidateResponse
         * @description Result of a connection check. ``message`` is operator-facing; ``detail``
         *     is an optional diagnostic. Neither ever contains a secret value.
         *
         *     For Plex, ``libraries`` carries the movie library folders so the UI can offer a
         *     pick-list for ``movies_root`` instead of a typed path. ``None`` for every other
         *     service (and for a failed Plex check).
         */
        ServiceValidateResponse: {
            /** Detail */
            detail?: string | null;
            /** Libraries */
            libraries?: components["schemas"]["PlexLibraryOption"][] | null;
            /** Message */
            message: string;
            /** Ok */
            ok: boolean;
        };
        /**
         * SettingsResponse
         * @description Redacted view of stored service config.
         *
         *     Plaintext (non-secret) values are returned as-is; secret values are shown as
         *     ``"***"`` when configured and ``None`` when unset — the plaintext secret is
         *     NEVER serialized.
         */
        SettingsResponse: {
            /** Movies Root */
            movies_root?: string | null;
            /** Plex Token */
            plex_token?: string | null;
            /** Plex Url */
            plex_url?: string | null;
            /** Prowlarr Api Key */
            prowlarr_api_key?: string | null;
            /** Prowlarr Url */
            prowlarr_url?: string | null;
            /** Qbittorrent Password */
            qbittorrent_password?: string | null;
            /** Qbittorrent Url */
            qbittorrent_url?: string | null;
            /** Qbittorrent Username */
            qbittorrent_username?: string | null;
            /** Tmdb Api Key */
            tmdb_api_key?: string | null;
        };
        /**
         * SettingsUpdate
         * @description Partial upsert of service config (``PUT /settings``).
         *
         *     Only fields present in the request body are written; secret fields are stored
         *     encrypted at rest. ``None`` / absent fields are left unchanged.
         */
        SettingsUpdate: {
            /** Movies Root */
            movies_root?: string | null;
            /** Plex Token */
            plex_token?: string | null;
            /** Plex Url */
            plex_url?: string | null;
            /** Prowlarr Api Key */
            prowlarr_api_key?: string | null;
            /** Prowlarr Url */
            prowlarr_url?: string | null;
            /** Qbittorrent Password */
            qbittorrent_password?: string | null;
            /** Qbittorrent Url */
            qbittorrent_url?: string | null;
            /** Qbittorrent Username */
            qbittorrent_username?: string | null;
            /** Tmdb Api Key */
            tmdb_api_key?: string | null;
        };
        /**
         * SetupCompleteRequest
         * @description The validated credential set written on ``POST /setup/complete``.
         */
        SetupCompleteRequest: {
            /** Movies Root */
            movies_root: string;
            /** Plex Token */
            plex_token: string;
            /** Plex Url */
            plex_url: string;
            /** Prowlarr Api Key */
            prowlarr_api_key: string;
            /** Prowlarr Url */
            prowlarr_url: string;
            /** Qbittorrent Password */
            qbittorrent_password: string;
            /** Qbittorrent Url */
            qbittorrent_url: string;
            /** Qbittorrent Username */
            qbittorrent_username: string;
            /** Tmdb Api Key */
            tmdb_api_key: string;
        };
        /**
         * SetupStatusResponse
         * @description Install state. ``app_api_key`` is populated only once initialized.
         */
        SetupStatusResponse: {
            /** App Api Key */
            app_api_key?: string | null;
            /** Initialized */
            initialized: boolean;
        };
        /**
         * TmdbValidateRequest
         * @description Candidate TMDB api key to test.
         */
        TmdbValidateRequest: {
            /** Api Key */
            api_key: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_blocklist_api_v1_blocklist_get: {
        parameters: {
            query?: {
                tmdb_id?: number | null;
                media_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlocklistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_blocklist_api_v1_blocklist__blocklist_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blocklist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_home_api_v1_discover_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverHomeResponse"];
                };
            };
        };
    };
    discover_search_api_v1_discover_search_get: {
        parameters: {
            query: {
                query: string;
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_category_api_v1_discover__category__get: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path: {
                category: "trending" | "popular" | "upcoming";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quality_profile_endpoint_api_v1_quality_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityProfileResponse"];
                };
            };
        };
    };
    get_queue_api_v1_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResponse"];
                };
            };
        };
    };
    grab_endpoint_api_v1_queue_grab_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrabRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_endpoint_api_v1_queue__download_id__import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                download_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_failed_endpoint_api_v1_queue__download_id__mark_failed_post: {
        parameters: {
            query?: {
                blocklist?: boolean;
            };
            header?: never;
            path: {
                download_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requests_endpoint_api_v1_requests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestListResponse"];
                };
            };
        };
    };
    create_request_endpoint_api_v1_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_request_endpoint_api_v1_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_preview_endpoint_api_v1_search_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_endpoint_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    put_settings_endpoint_api_v1_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plex_libraries_endpoint_api_v1_settings_plex_libraries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlexLibraryOption"][];
                };
            };
        };
    };
    complete_api_v1_setup_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupCompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_v1_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusResponse"];
                };
            };
        };
    };
    validate_plex_endpoint_api_v1_setup_validate_plex_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlexValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_prowlarr_endpoint_api_v1_setup_validate_prowlarr_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProwlarrValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_qbittorrent_endpoint_api_v1_setup_validate_qbittorrent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QbittorrentValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_tmdb_endpoint_api_v1_setup_validate_tmdb_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TmdbValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
