/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/blocklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Blocklist
         * @description List blocklist entries, optionally scoped to one media item.
         */
        get: operations["list_blocklist_api_v1_blocklist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blocklist/{blocklist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Blocklist
         * @description Remove a blocklist entry (operator un-blocklist).
         */
        delete: operations["delete_blocklist_api_v1_blocklist__blocklist_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/discover/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover Home
         * @description Return the server-composed Discover home (spotlight + ordered rows).
         */
        get: operations["discover_home_api_v1_discover_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/discover/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover Search
         * @description Search TMDB for movies / shows matching ``query`` (optional ``year``).
         */
        get: operations["discover_search_api_v1_discover_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/discover/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover Category
         * @description Return a paginated movie category (``trending`` / ``popular`` / ``upcoming``).
         */
        get: operations["discover_category_api_v1_discover__category__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/disk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Disk Endpoint
         * @description Disk usage per configured library root, plus a ranked preview of what a
         *     pressure sweep WOULD evict from each (never evicts anything itself).
         *
         *     TTL-cached per root (~15s) — see :func:`_disk_root_item` — so the Status
         *     page's ~15s poll never re-hammers Plex/the filesystem on every tick.
         */
        get: operations["disk_endpoint_api_v1_ops_disk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/evict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evict Endpoint
         * @description Manually trigger a pressure-triggered eviction sweep across every
         *     configured root — the north-star #1 button: free space on demand.
         *
         *     Runs REGARDLESS of the ``eviction_enabled`` master switch: that setting
         *     gates the AUTOMATIC periodic sweep (``web/app.py``'s ``_eviction_tick``),
         *     never this explicit, operator-initiated action — an operator who disabled
         *     the background loop must still be able to free space on demand without
         *     re-enabling it. Still pressure-gated (a root already below
         *     ``disk_pressure_threshold_percent`` evicts nothing — an empty ``evicted``
         *     is a normal, honest outcome) and still honours every other rule (watched,
         *     past grace, un-pinned, not in flight): this is the SAME sweep the periodic
         *     task runs, just invoked synchronously instead of on a timer. Requires Plex
         *     (409 ``service_not_configured`` otherwise — watch state can't be resolved
         *     without it); an unset root is simply skipped, not an error.
         *
         *     Invalidates :func:`_get_disk_preview_cache` after the sweep: without this,
         *     ``GET /disk`` would keep serving the pre-eviction snapshot (stale
         *     candidates the operator just deleted, stale free-space gauge) for up to
         *     its ~15s TTL, contradicting north-star #3 for the very endpoint that IS
         *     the correction button.
         *
         *     Each root's sweep is INDEPENDENT: one root raising (e.g. a transient
         *     ``PlexLibraryError`` resolving TV watch state during candidate assembly)
         *     must never abort a root that has not run yet, nor hide what an EARLIER
         *     root already deleted and committed. A bare 500 here would do exactly that
         *     — the operator would see "Free space failed" with no indication that,
         *     say, the movies root already freed real space — which is a dishonest,
         *     silent-partial-success state north star #2 forbids. So every root's sweep
         *     is individually caught; a caught failure is logged and recorded in
         *     ``errors`` (never swallowed), ``evicted`` still lists whatever succeeded,
         *     and the endpoint ALWAYS reaches ``cache.clear()`` and returns 200 —
         *     partial completion is a first-class, visible outcome, not a terminal one.
         */
        post: operations["evict_endpoint_api_v1_ops_evict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Endpoint
         * @description One read: per-subsystem reachability, disk gauges, and the reconcile
         *     loop's own health. Each upstream probe is TTL-cached (~15s) so polling this
         *     every few seconds never hammers an upstream or burns the TMDB rate limit.
         */
        get: operations["health_endpoint_api_v1_ops_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Logs Endpoint
         * @description Paginated, filtered read of the durable ``log_events`` store, newest
         *     first. ``correlation_id`` matches a ``request_id``/``download_id``/
         *     ``tmdb_id`` carried in a record's context.
         */
        get: operations["list_logs_endpoint_api_v1_ops_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/logs/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Logs Endpoint
         * @description The LLM-diagnosis affordance: one coherent, downloadable/copyable trail.
         *
         *     Either a single correlation id's FULL history (``correlation_id`` — a
         *     ``request_id``/``download_id``/``tmdb_id``), or a time window from
         *     ``since`` through now (``since`` omitted defaults to the last 24h) — when
         *     both are supplied, ``correlation_id`` wins (a specific id's whole trail is
         *     the more precise ask). Bounded to :data:`_MAX_EXPORT_ROWS` (an internal
         *     safety cap, not a policy setting) with an honest trailing note when
         *     truncated. Rendered OLDEST-first (a coherent top-to-bottom story), unlike
         *     the newest-first ``GET /logs`` list. ``Content-Disposition: attachment`` so
         *     navigating straight to this URL downloads a file; a caller reading the body
         *     via ``fetch`` (the frontend's "copy to clipboard") is unaffected by the header.
         */
        get: operations["export_logs_endpoint_api_v1_ops_logs_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/logs/tail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tail Logs Endpoint
         * @description The live, in-memory, ALL-levels ring-buffer tail (newest first) — lost on
         *     restart, never persisted (only INFO+ reaches durable ``log_events``, see
         *     ``GET /logs`` above). ``dropped_count`` is the capture handler's own honest
         *     signal for how many INFO+ records missed durable storage since startup.
         */
        get: operations["tail_logs_endpoint_api_v1_ops_logs_tail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quality-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quality Profile Endpoint
         * @description Return the alpha default quality profile (ordered low -> high, with cutoff).
         */
        get: operations["get_quality_profile_endpoint_api_v1_quality_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Queue
         * @description Return the live download queue (read-only).
         *
         *     Passive by design: the background reconcile loop is the single owner of
         *     cross-system truth, so a queue poll never reconciles — doing so could race the
         *     loop's importer CAS and clobber an ``importing`` claim. The loop refreshes
         *     frequently, so the persisted progress/status is fresh enough to display, and the
         *     queue stays viewable even while qBittorrent is unreachable.
         */
        get: operations["get_queue_api_v1_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/grab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grab Endpoint
         * @description Grab a release for a request: a chosen one, or the top accepted pick.
         */
        post: operations["grab_endpoint_api_v1_queue_grab_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/{download_id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Endpoint
         * @description Operator retry: (re)run the import for a download (e.g. an ImportBlocked row).
         *
         *     Requires Plex + qBittorrent configured (409 ``service_not_configured``
         *     otherwise); the Movies/TV roots are each OPTIONAL here -- no upfront 409 for
         *     either. A download whose media type's root is unset gets its own honest,
         *     retryable ``ImportBlocked`` (surfaced in the returned ``QueueItem``, a normal
         *     200) instead of the endpoint refusing to even try, so an install with only
         *     ONE root configured can still retry-import that type. The
         *     correction-without-a-terminal button for a blocked import.
         */
        post: operations["import_endpoint_api_v1_queue__download_id__import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/{download_id}/mark-failed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Failed Endpoint
         * @description Operator move: mark a download failed (optionally blocklisting the release).
         */
        post: operations["mark_failed_endpoint_api_v1_queue__download_id__mark_failed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Requests Endpoint
         * @description List all media requests.
         */
        get: operations["list_requests_endpoint_api_v1_requests_get"];
        put?: never;
        /**
         * Create Request Endpoint
         * @description Create a request (or return the existing active one for this media).
         *
         *     If Plex is configured and the movie is already in the library, the request is
         *     recorded directly as ``available`` (no needless search/grab). For a tv
         *     request, ``body.seasons`` (omitted/empty = the whole aired series) is threaded
         *     to ``request_service.create_request``, which tracks each named season as its
         *     own ``SeasonRequest`` row -- including on the dedup path, where a repeat POST
         *     with a NEW season list grows the tracked set rather than being dropped.
         */
        post: operations["create_request_endpoint_api_v1_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Request Endpoint
         * @description Return a single media request, or 404.
         */
        get: operations["get_request_endpoint_api_v1_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requests/{request_id}/keep-forever": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Keep Forever Endpoint
         * @description Set or clear the operator's "keep forever" pin (ADR-0012).
         *
         *     The north-star #1 correction path for "don't let the eviction sweep touch
         *     this one": a pinned title (or, for a show, every one of its seasons -- the
         *     pin lives on the parent) is never selected by ``domain/eviction.py``
         *     regardless of watch state or disk pressure. A 404 for an unknown id, never
         *     a silent no-op.
         */
        post: operations["keep_forever_endpoint_api_v1_requests__request_id__keep_forever_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Preview Endpoint
         * @description Run the decision engine over the indexer results for this media.
         */
        post: operations["search_preview_endpoint_api_v1_search_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings Endpoint
         * @description Return the redacted service config (secrets shown as ``"***"``).
         */
        get: operations["get_settings_endpoint_api_v1_settings_get"];
        /**
         * Put Settings Endpoint
         * @description Upsert the provided config and return the redacted result.
         *
         *     A secret field whose incoming value is the redaction mask (``"***"``) is a
         *     no-op: GET returns ``"***"`` for a configured secret, so a FE that round-trips
         *     the whole object back (e.g. after editing only ``plex_url``) must not clobber
         *     the real credential with the mask — a silent secret-wipe that would only
         *     surface later as an auth failure to the downstream service.
         *
         *     The disk-pressure pair is cross-checked against the EFFECTIVE (post-update)
         *     values, not just what this one request happens to carry: ``SettingsUpdate``'s
         *     own ``model_validator`` only catches a target above the threshold when BOTH
         *     are submitted together, but ``PUT`` is a PARTIAL update — sending just one
         *     side against an already-stored (and now-inverted) other side would otherwise
         *     silently leave the whole threshold-to-target band unable to relieve pressure
         *     (see :func:`~plex_manager.web.routers.settings._validate_disk_pressure_pair`).
         *     Checked, and rejected with the SAME 422 shape, BEFORE anything is written.
         */
        put: operations["put_settings_endpoint_api_v1_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/plex-libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plex Libraries Endpoint
         * @description Library folders (movie AND tv) Plex reports, for the Settings
         *     ``movies_root`` / ``tv_root`` pickers -- each option is tagged by
         *     ``section_type`` so the frontend can filter to the picker it's rendering.
         *
         *     Uses the stored Plex creds (no re-typing the token); 409 if Plex is unconfigured.
         */
        get: operations["plex_libraries_endpoint_api_v1_settings_plex_libraries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete
         * @description Persist the validated creds, mint the app api key, mark initialized.
         *
         *     One-shot AND concurrency-safe: rejected with 409 once initialized. Two
         *     concurrent ``/complete`` calls can both pass an in-memory ``initialized`` check
         *     and double-write (a ``settings.key`` unique-constraint 500, or one overwriting
         *     the other's just-issued ``app_api_key``). To prevent that, initialization is
         *     claimed with a CONDITIONAL update (``... WHERE id = 1 AND initialized = false``):
         *     exactly one request flips the row, and the loser sees ``rowcount == 0`` and is
         *     rejected 409 — so only the winner mints the key and writes the creds. Re-running
         *     setup post-init would also let an unauthenticated caller overwrite every stored
         *     credential and re-disclose the app key, so post-init changes must go through the
         *     authenticated ``PUT /settings``.
         */
        post: operations["complete_api_v1_setup_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status
         * @description Report install state only — never the app api key.
         *
         *     The key is revealed exactly once, in the ``/complete`` response (the SPA
         *     persists it then). Re-serving it from this unauthenticated GET would hand any
         *     anonymous caller the master ``X-Api-Key`` post-init, nullifying the entire
         *     auth model, so ``app_api_key`` is always ``None`` here.
         */
        get: operations["status_api_v1_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/validate/plex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Plex Endpoint
         * @description Test candidate Plex credentials.
         */
        post: operations["validate_plex_endpoint_api_v1_setup_validate_plex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/validate/prowlarr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Prowlarr Endpoint
         * @description Test candidate Prowlarr credentials.
         */
        post: operations["validate_prowlarr_endpoint_api_v1_setup_validate_prowlarr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/validate/qbittorrent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Qbittorrent Endpoint
         * @description Test candidate qBittorrent credentials.
         */
        post: operations["validate_qbittorrent_endpoint_api_v1_setup_validate_qbittorrent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/validate/tmdb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Tmdb Endpoint
         * @description Test a candidate TMDB api key.
         */
        post: operations["validate_tmdb_endpoint_api_v1_setup_validate_tmdb_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe used by the container healthcheck and monitoring.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcceptedRelease
         * @description A release that passed the quality gate and blocklist, with its ranking.
         */
        AcceptedRelease: {
            /** Guid */
            guid: string;
            /** Indexer */
            indexer: string;
            /** Info Hash */
            info_hash?: string | null;
            /** Quality Name */
            quality_name: string;
            /** Resolution */
            resolution: string;
            /** Score */
            score: number;
            /** Seeders */
            seeders?: number | null;
            /** Source */
            source: string;
            /** Title */
            title: string;
        };
        /**
         * BlocklistEntry
         * @description A blocklist entry as returned to the client.
         */
        BlocklistEntry: {
            /** Added At */
            added_at?: string | null;
            /** Id */
            id: number;
            /** Indexer */
            indexer?: string | null;
            /** Media Type */
            media_type?: string | null;
            /** Protocol */
            protocol?: string | null;
            /** Reason */
            reason: string;
            /** Source Title */
            source_title: string;
            /** Tmdb Id */
            tmdb_id?: number | null;
            /** Torrent Hash */
            torrent_hash?: string | null;
        };
        /**
         * BlocklistResponse
         * @description A list of blocklist entries.
         */
        BlocklistResponse: {
            /** Entries */
            entries: components["schemas"]["BlocklistEntry"][];
        };
        /**
         * CreateRequestBody
         * @description Create a media request by tmdb id + media type.
         */
        CreateRequestBody: {
            /**
             * Media Type
             * @enum {string}
             */
            media_type: "movie" | "tv";
            /** Seasons */
            seasons?: number[] | null;
            /** Tmdb Id */
            tmdb_id: number;
        };
        /**
         * DiscoverHomeResponse
         * @description The composed Discover home: an optional spotlight + ordered rows.
         */
        DiscoverHomeResponse: {
            /** Rows */
            rows: components["schemas"]["DiscoverHomeRow"][];
            spotlight?: components["schemas"]["DiscoverResult"] | null;
        };
        /**
         * DiscoverHomeRow
         * @description One server-composed Discover row: a title + its items.
         *
         *     ``row_type`` is an OPEN string (e.g. ``trending`` / ``popular`` / ``upcoming``)
         *     so the frontend renders rows generically and stays dumb about WHY a row exists
         *     — TV and recommendation rows slot in later with no contract change.
         */
        DiscoverHomeRow: {
            /** Items */
            items: components["schemas"]["DiscoverResult"][];
            /** Row Type */
            row_type: string;
            /** Title */
            title: string;
        };
        /**
         * DiscoverListResponse
         * @description A paginated category listing (trending / popular / upcoming).
         */
        DiscoverListResponse: {
            /** Page */
            page: number;
            /** Results */
            results: components["schemas"]["DiscoverResult"][];
            /** Total Pages */
            total_pages: number;
            /** Total Results */
            total_results: number;
        };
        /**
         * DiscoverResult
         * @description One discovery search row.
         */
        DiscoverResult: {
            /** Backdrop Url */
            backdrop_url?: string | null;
            /**
             * Media Type
             * @enum {string}
             */
            media_type: "movie" | "tv";
            /** Overview */
            overview?: string | null;
            /** Poster Url */
            poster_url?: string | null;
            /** Title */
            title: string;
            /** Tmdb Id */
            tmdb_id: number;
            /** Year */
            year?: number | null;
        };
        /**
         * DiscoverSearchResponse
         * @description The discovery search result set.
         */
        DiscoverSearchResponse: {
            /** Results */
            results: components["schemas"]["DiscoverResult"][];
        };
        /**
         * DiskGaugeItem
         * @description One configured library root's usage snapshot (health dashboard gauge).
         */
        DiskGaugeItem: {
            /** Available Bytes */
            available_bytes: number;
            /** Error */
            error?: string | null;
            /** Path */
            path: string;
            /** Root */
            root: string;
            /** Total Bytes */
            total_bytes: number;
            /** Used Percent */
            used_percent: number;
        };
        /**
         * DiskResponse
         * @description ``GET /api/v1/ops/disk`` -- usage + a ranked eviction-candidate preview
         *     per configured root.
         */
        DiskResponse: {
            /** Roots */
            roots: components["schemas"]["DiskRootItem"][];
        };
        /**
         * DiskRootItem
         * @description One configured library root's usage + its ranked eviction preview.
         */
        DiskRootItem: {
            /** Available Bytes */
            available_bytes: number;
            /** Candidates */
            candidates: components["schemas"]["EvictionCandidateItem"][];
            /** Error */
            error?: string | null;
            /** Path */
            path: string;
            /** Root */
            root: string;
            /** Total Bytes */
            total_bytes: number;
            /** Used Percent */
            used_percent: number;
        };
        /**
         * EvictErrorItem
         * @description One root's sweep failure inside a manual ``POST /api/v1/ops/evict`` --
         *     a LATER root raising (e.g. a transient Plex error resolving TV watch
         *     state) must never hide an EARLIER root's evictions that already deleted
         *     files and committed (honesty over silence: partial progress is surfaced,
         *     not swallowed behind a 500).
         */
        EvictErrorItem: {
            /** Detail */
            detail: string;
            /**
             * Root
             * @enum {string}
             */
            root: "movies_root" | "tv_root";
        };
        /**
         * EvictResponse
         * @description The result of a manual disk-pressure sweep (north-star #1: a button that
         *     frees space on demand). Empty ``evicted`` is a normal, honest outcome (no
         *     root was under pressure, or nothing was eligible). ``errors`` is populated
         *     per-root when THAT root's own sweep raised -- every other root's outcome
         *     in ``evicted`` still stands; the sweep never aborts one root's already
         *     committed work just because a sibling root failed.
         */
        EvictResponse: {
            /** Errors */
            errors?: components["schemas"]["EvictErrorItem"][];
            /** Evicted */
            evicted: components["schemas"]["EvictionOutcomeItem"][];
        };
        /**
         * EvictionCandidateItem
         * @description One title/season a pressure sweep WOULD evict (the ``GET /ops/disk``
         *     preview), or one it DID evict (a ``POST /ops/evict`` outcome shares this
         *     shape's fields, see :class:`EvictionOutcomeItem`).
         */
        EvictionCandidateItem: {
            /** Last Viewed At */
            last_viewed_at?: string | null;
            /** Library Path */
            library_path?: string | null;
            /**
             * Media Type
             * @enum {string}
             */
            media_type: "movie" | "tv";
            /** Request Id */
            request_id: number;
            /** Season */
            season?: number | null;
            /** Size Percent */
            size_percent: number;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /**
         * EvictionOutcomeItem
         * @description One candidate a manual ``POST /api/v1/ops/evict`` sweep actually evicted.
         */
        EvictionOutcomeItem: {
            /** Freed Bytes */
            freed_bytes?: number | null;
            /** Library Path */
            library_path: string;
            /**
             * Media Type
             * @enum {string}
             */
            media_type: "movie" | "tv";
            /** Request Id */
            request_id: number;
            /** Season */
            season?: number | null;
            /** Title */
            title: string;
        };
        /**
         * GrabRequest
         * @description Grab a release for a request: a chosen ``info_hash``/``guid`` or the top pick.
         *
         *     With neither ``info_hash`` nor ``guid`` set, the highest-ranked accepted
         *     release is grabbed ("grab top"). For a TV request, ``season`` scopes both the
         *     indexer search and the stored download to that season; ``episodes`` further
         *     scopes it to those specific episode number(s) (``None``/empty = the whole
         *     season). Every TV grab is per-season: the endpoint REJECTS (422) a tv request
         *     grabbed with no ``season``, and REJECTS (422) a non-tv (movie) request grabbed
         *     WITH a ``season`` -- the branch is always the request's actual media type,
         *     never merely whether ``season`` happens to be set.
         */
        GrabRequest: {
            /** Episodes */
            episodes?: number[] | null;
            /** Guid */
            guid?: string | null;
            /** Info Hash */
            info_hash?: string | null;
            /** Request Id */
            request_id: number;
            /** Season */
            season?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description ``GET /api/v1/ops/health`` -- one read answering "is every subsystem
         *     healthy, is the reconcile loop running, how full is the disk".
         */
        HealthResponse: {
            /** Disks */
            disks: components["schemas"]["DiskGaugeItem"][];
            reconcile: components["schemas"]["ReconcileStatusItem"];
            /** Subsystems */
            subsystems: components["schemas"]["SubsystemHealthItem"][];
        };
        /**
         * KeepForeverBody
         * @description ``POST /api/v1/requests/{id}/keep-forever`` -- set or clear the pin.
         */
        KeepForeverBody: {
            /** Keep Forever */
            keep_forever: boolean;
        };
        /**
         * LiveLogRecordItem
         * @description One entry from the in-memory, all-levels live tail ring buffer.
         *
         *     Unlike :class:`LogEventItem`, this has no durable row id -- the ring buffer
         *     is lost on restart and never persisted (only INFO-and-above reaches
         *     ``log_events``; this endpoint shows EVERY level, including DEBUG).
         */
        LiveLogRecordItem: {
            /** Context */
            context?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Level */
            level: string;
            /** Logger */
            logger: string;
            /** Message */
            message: string;
        };
        /**
         * LogEventItem
         * @description One durably-stored ``log_events`` row, as the log viewer / export reads it.
         *
         *     ``context`` carries correlation ids (``request_id``/``download_id``/
         *     ``tmdb_id``) set at the log call site -- never a secret-bearing field (see
         *     ``models.LogEvent``).
         */
        LogEventItem: {
            /** Context */
            context?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Level */
            level: string;
            /** Logger */
            logger: string;
            /** Message */
            message: string;
        };
        /**
         * LogsResponse
         * @description A filtered, paginated page of ``GET /api/v1/ops/logs``.
         *
         *     ``total`` is the count of rows matching the filter (not the whole table),
         *     so the client can tell whether more pages exist beyond ``events``.
         */
        LogsResponse: {
            /** Events */
            events: components["schemas"]["LogEventItem"][];
            /** Total */
            total: number;
        };
        /**
         * LogsTailResponse
         * @description ``GET /api/v1/ops/logs/tail`` -- the live ring buffer, newest first.
         *
         *     ``dropped_count`` is the capture handler's own honest signal: how many
         *     INFO+ records could not be enqueued for durable storage since startup
         *     because the drain queue was full (the ring buffer itself is unaffected --
         *     see ``LogCaptureHandler``'s docstring).
         */
        LogsTailResponse: {
            /** Dropped Count */
            dropped_count: number;
            /** Events */
            events: components["schemas"]["LiveLogRecordItem"][];
        };
        /**
         * PlexLibraryOption
         * @description One movie- OR tv-library folder Plex reports, with whether the app can write to it.
         *
         *     ``path`` is a Plex library location (from Plex's own ``/library/sections``), so
         *     choosing it for ``movies_root`` / ``tv_root`` avoids a typed path entirely (and
         *     the path↔section mismatch that breaks a targeted scan). ``section_type`` tags
         *     which root this option is for (``"movie"`` -> ``movies_root``, ``"tv"`` ->
         *     ``tv_root``) so a single generalized list can drive both pickers. ``writable``
         *     is the app's own check (``None`` when not probed — see the field): a
         *     known-not-writable location is the split-mount signal — surfaced, not hidden.
         */
        PlexLibraryOption: {
            /** Path */
            path: string;
            /** Section Key */
            section_key: string;
            /**
             * Section Type
             * @enum {string}
             */
            section_type: "movie" | "tv";
            /** Title */
            title: string;
            /** Writable */
            writable?: boolean | null;
        };
        /**
         * PlexValidateRequest
         * @description Candidate Plex credentials to test (``POST /setup/validate/plex``).
         */
        PlexValidateRequest: {
            /** Token */
            token: string;
            /** Url */
            url: string;
        };
        /**
         * ProwlarrValidateRequest
         * @description Candidate Prowlarr credentials to test.
         */
        ProwlarrValidateRequest: {
            /** Api Key */
            api_key: string;
            /** Url */
            url: string;
        };
        /**
         * QbittorrentValidateRequest
         * @description Candidate qBittorrent credentials to test.
         */
        QbittorrentValidateRequest: {
            /** Password */
            password: string;
            /** Url */
            url: string;
            /** Username */
            username: string;
        };
        /**
         * QualityProfileItemResponse
         * @description One ordered entry in the quality profile.
         */
        QualityProfileItemResponse: {
            /** Allowed */
            allowed: boolean;
            /** Name */
            name: string;
            /** Quality Id */
            quality_id: number;
            /** Resolution */
            resolution: string;
            /** Source */
            source: string;
        };
        /**
         * QualityProfileResponse
         * @description The serialized default quality profile (ordered low -> high, with cutoff).
         */
        QualityProfileResponse: {
            /** Cutoff Name */
            cutoff_name: string;
            /** Cutoff Quality Id */
            cutoff_quality_id: number;
            /** Id */
            id: number;
            /** Items */
            items: components["schemas"]["QualityProfileItemResponse"][];
            /** Name */
            name: string;
            /** Upgrade Allowed */
            upgrade_allowed: boolean;
        };
        /**
         * QueueItem
         * @description A tracked download in the live queue.
         */
        QueueItem: {
            /** Episodes */
            episodes?: number[] | null;
            /** Failed Reason */
            failed_reason?: string | null;
            /** Id */
            id: number;
            /** Media Request Id */
            media_request_id?: number | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Season */
            season?: number | null;
            /**
             * Seed Ratio
             * @default 0
             */
            seed_ratio: number;
            /** Status */
            status: string;
            /** Tmdb Id */
            tmdb_id?: number | null;
            /** Torrent Hash */
            torrent_hash: string;
        };
        /**
         * QueueResponse
         * @description The reconciled download queue.
         */
        QueueResponse: {
            /** Queue */
            queue: components["schemas"]["QueueItem"][];
        };
        /**
         * ReconcileStatusItem
         * @description The background reconcile loop's own health, mirrored from
         *     ``services.health_service.ReconcileStatusSnapshot``. Deliberately separate
         *     from the subsystem cards above -- a cycle can complete OK even while one
         *     upstream inside it degraded (see that class's docstring).
         */
        ReconcileStatusItem: {
            /**
             * Consecutive Failures
             * @default 0
             */
            consecutive_failures: number;
            /** Last Error At */
            last_error_at?: string | null;
            /** Last Error Type */
            last_error_type?: string | null;
            /** Last Ok At */
            last_ok_at?: string | null;
            /** Last Run At */
            last_run_at?: string | null;
        };
        /**
         * RejectedRelease
         * @description A discarded release paired with its surfaced rejection reason.
         */
        RejectedRelease: {
            /** Reason */
            reason: string;
            /** Title */
            title: string;
        };
        /**
         * RequestListResponse
         * @description A list of media requests.
         */
        RequestListResponse: {
            /** Requests */
            requests: components["schemas"]["RequestResponse"][];
        };
        /**
         * RequestResponse
         * @description A media request as returned to the client.
         */
        RequestResponse: {
            /** Backdrop Url */
            backdrop_url?: string | null;
            /** Id */
            id: number;
            /**
             * Is Anime
             * @default false
             */
            is_anime: boolean;
            /**
             * Keep Forever
             * @default false
             */
            keep_forever: boolean;
            /** Media Type */
            media_type: string;
            /** Poster Url */
            poster_url?: string | null;
            /** Seasons */
            seasons?: components["schemas"]["SeasonStatus"][] | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Tmdb Id */
            tmdb_id: number;
            /** Year */
            year?: number | null;
        };
        /**
         * SearchPreviewRequest
         * @description Preview by ``request_id`` OR by an explicit media descriptor.
         *
         *     When ``request_id`` is set the other fields are ignored (resolved from the
         *     stored request). Otherwise ``tmdb_id``, ``media_type`` and ``title`` are
         *     required.
         */
        SearchPreviewRequest: {
            /** Episodes */
            episodes?: number[] | null;
            /** Media Type */
            media_type?: ("movie" | "tv") | null;
            /** Request Id */
            request_id?: number | null;
            /** Season */
            season?: number | null;
            /** Title */
            title?: string | null;
            /** Tmdb Id */
            tmdb_id?: number | null;
            /** Year */
            year?: number | null;
        };
        /**
         * SearchPreviewResponse
         * @description Ranked accepted releases, per-release rejections, and the empty-set flag.
         */
        SearchPreviewResponse: {
            /** Accepted */
            accepted: components["schemas"]["AcceptedRelease"][];
            /** No Acceptable Release */
            no_acceptable_release: boolean;
            /** Rejected */
            rejected: components["schemas"]["RejectedRelease"][];
        };
        /**
         * SeasonStatus
         * @description One tracked season's status, embedded in a tv ``RequestResponse``.
         */
        SeasonStatus: {
            /** Season Number */
            season_number: number;
            /** Status */
            status: string;
        };
        /**
         * ServiceValidateResponse
         * @description Result of a connection check. ``message`` is operator-facing; ``detail``
         *     is an optional diagnostic. Neither ever contains a secret value.
         *
         *     For Plex, ``libraries`` carries the movie AND tv library folders (each tagged
         *     by ``section_type``) so the UI can offer pick-lists for ``movies_root`` /
         *     ``tv_root`` instead of a typed path. ``None`` for every other service (and for
         *     a failed Plex check).
         */
        ServiceValidateResponse: {
            /** Detail */
            detail?: string | null;
            /** Libraries */
            libraries?: components["schemas"]["PlexLibraryOption"][] | null;
            /** Message */
            message: string;
            /** Ok */
            ok: boolean;
        };
        /**
         * SettingsResponse
         * @description Redacted view of stored service config.
         *
         *     Plaintext (non-secret) values are returned as-is; secret values are shown as
         *     ``"***"`` when configured and ``None`` when unset — the plaintext secret is
         *     NEVER serialized.
         */
        SettingsResponse: {
            /** Disk Pressure Target Percent */
            disk_pressure_target_percent?: number | null;
            /** Disk Pressure Threshold Percent */
            disk_pressure_threshold_percent?: number | null;
            /** Eviction Enabled */
            eviction_enabled?: boolean | null;
            /** Eviction Grace Days */
            eviction_grace_days?: number | null;
            /** Eviction Interval Minutes */
            eviction_interval_minutes?: number | null;
            /** Eviction Proactive Enabled */
            eviction_proactive_enabled?: boolean | null;
            /** Log Retention Days */
            log_retention_days?: number | null;
            /** Movies Root */
            movies_root?: string | null;
            /** Plex Token */
            plex_token?: string | null;
            /** Plex Url */
            plex_url?: string | null;
            /** Prowlarr Api Key */
            prowlarr_api_key?: string | null;
            /** Prowlarr Url */
            prowlarr_url?: string | null;
            /** Qbittorrent Password */
            qbittorrent_password?: string | null;
            /** Qbittorrent Url */
            qbittorrent_url?: string | null;
            /** Qbittorrent Username */
            qbittorrent_username?: string | null;
            /** Tmdb Api Key */
            tmdb_api_key?: string | null;
            /** Tv Root */
            tv_root?: string | null;
        };
        /**
         * SettingsUpdate
         * @description Partial upsert of service config (``PUT /settings``).
         *
         *     Only fields present in the request body are written; secret fields are stored
         *     encrypted at rest. ``None`` / absent fields are left unchanged.
         */
        SettingsUpdate: {
            /** Disk Pressure Target Percent */
            disk_pressure_target_percent?: number | null;
            /** Disk Pressure Threshold Percent */
            disk_pressure_threshold_percent?: number | null;
            /** Eviction Enabled */
            eviction_enabled?: boolean | null;
            /** Eviction Grace Days */
            eviction_grace_days?: number | null;
            /** Eviction Interval Minutes */
            eviction_interval_minutes?: number | null;
            /** Eviction Proactive Enabled */
            eviction_proactive_enabled?: boolean | null;
            /** Log Retention Days */
            log_retention_days?: number | null;
            /** Movies Root */
            movies_root?: string | null;
            /** Plex Token */
            plex_token?: string | null;
            /** Plex Url */
            plex_url?: string | null;
            /** Prowlarr Api Key */
            prowlarr_api_key?: string | null;
            /** Prowlarr Url */
            prowlarr_url?: string | null;
            /** Qbittorrent Password */
            qbittorrent_password?: string | null;
            /** Qbittorrent Url */
            qbittorrent_url?: string | null;
            /** Qbittorrent Username */
            qbittorrent_username?: string | null;
            /** Tmdb Api Key */
            tmdb_api_key?: string | null;
            /** Tv Root */
            tv_root?: string | null;
        };
        /**
         * SetupCompleteRequest
         * @description The validated credential set written on ``POST /setup/complete``.
         */
        SetupCompleteRequest: {
            /** Movies Root */
            movies_root: string;
            /** Plex Token */
            plex_token: string;
            /** Plex Url */
            plex_url: string;
            /** Prowlarr Api Key */
            prowlarr_api_key: string;
            /** Prowlarr Url */
            prowlarr_url: string;
            /** Qbittorrent Password */
            qbittorrent_password: string;
            /** Qbittorrent Url */
            qbittorrent_url: string;
            /** Qbittorrent Username */
            qbittorrent_username: string;
            /** Tmdb Api Key */
            tmdb_api_key: string;
            /** Tv Root */
            tv_root?: string | null;
        };
        /**
         * SetupStatusResponse
         * @description Install state. ``app_api_key`` is populated only once initialized.
         */
        SetupStatusResponse: {
            /** App Api Key */
            app_api_key?: string | null;
            /** Initialized */
            initialized: boolean;
        };
        /**
         * SubsystemHealthItem
         * @description One upstream's reachability, as ``services.health_service.SubsystemHealth``
         *     reports it. ``not_configured`` is honest -- never confused with ``down``.
         */
        SubsystemHealthItem: {
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Detail */
            detail?: string | null;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "down" | "not_configured";
        };
        /**
         * TmdbValidateRequest
         * @description Candidate TMDB api key to test.
         */
        TmdbValidateRequest: {
            /** Api Key */
            api_key: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_blocklist_api_v1_blocklist_get: {
        parameters: {
            query?: {
                tmdb_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlocklistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_blocklist_api_v1_blocklist__blocklist_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blocklist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_home_api_v1_discover_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverHomeResponse"];
                };
            };
        };
    };
    discover_search_api_v1_discover_search_get: {
        parameters: {
            query: {
                query: string;
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_category_api_v1_discover__category__get: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path: {
                category: "trending" | "popular" | "upcoming" | "trending_tv" | "popular_tv";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disk_endpoint_api_v1_ops_disk_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiskResponse"];
                };
            };
        };
    };
    evict_endpoint_api_v1_ops_evict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvictResponse"];
                };
            };
        };
    };
    health_endpoint_api_v1_ops_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_logs_endpoint_api_v1_ops_logs_get: {
        parameters: {
            query?: {
                level?: string | null;
                since?: string | null;
                logger?: string | null;
                correlation_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_logs_endpoint_api_v1_ops_logs_export_get: {
        parameters: {
            query?: {
                correlation_id?: string | null;
                since?: string | null;
                format?: "text" | "json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Either a `text/plain` line-per-event trail (default, `format=text`) or a JSON `LogsResponse` bundle (`format=json`) — the two shapes this endpoint actually serves, per the `format` query parameter. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsResponse"];
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tail_logs_endpoint_api_v1_ops_logs_tail_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsTailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quality_profile_endpoint_api_v1_quality_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityProfileResponse"];
                };
            };
        };
    };
    get_queue_api_v1_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResponse"];
                };
            };
        };
    };
    grab_endpoint_api_v1_queue_grab_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrabRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_endpoint_api_v1_queue__download_id__import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                download_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_failed_endpoint_api_v1_queue__download_id__mark_failed_post: {
        parameters: {
            query?: {
                blocklist?: boolean;
            };
            header?: never;
            path: {
                download_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requests_endpoint_api_v1_requests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestListResponse"];
                };
            };
        };
    };
    create_request_endpoint_api_v1_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_request_endpoint_api_v1_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    keep_forever_endpoint_api_v1_requests__request_id__keep_forever_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeepForeverBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_preview_endpoint_api_v1_search_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_endpoint_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    put_settings_endpoint_api_v1_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plex_libraries_endpoint_api_v1_settings_plex_libraries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlexLibraryOption"][];
                };
            };
        };
    };
    complete_api_v1_setup_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupCompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_v1_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusResponse"];
                };
            };
        };
    };
    validate_plex_endpoint_api_v1_setup_validate_plex_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlexValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_prowlarr_endpoint_api_v1_setup_validate_prowlarr_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProwlarrValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_qbittorrent_endpoint_api_v1_setup_validate_qbittorrent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QbittorrentValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_tmdb_endpoint_api_v1_setup_validate_tmdb_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TmdbValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
