"""add media_requests available_heal_verified_at

Revision ID: 1b661e856ac1
Revises: c86212dad733
Create Date: 2026-07-11 21:17:49.388058
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b661e856ac1"
down_revision: str | None = "c86212dad733"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media_requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("available_heal_verified_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media_requests", schema=None) as batch_op:
        batch_op.drop_column("available_heal_verified_at")

    # ### end Alembic commands ###
