"""eviction regrab provenance marker

Revision ID: 26d44ca5f471
Revises: 7bcbce2c2e2b
Create Date: 2026-07-07 10:31:00.751149
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26d44ca5f471"
down_revision: str | None = "7bcbce2c2e2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("eviction_regrab", sa.Boolean(), nullable=True))

    with op.batch_alter_table("season_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("eviction_regrab", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("season_requests", schema=None) as batch_op:
        batch_op.drop_column("eviction_regrab")

    with op.batch_alter_table("media_requests", schema=None) as batch_op:
        batch_op.drop_column("eviction_regrab")

    # ### end Alembic commands ###
