"""initial schema

Revision ID: 309cbf9239c3
Revises: 
Create Date: 2026-06-29 19:48:05.922806
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309cbf9239c3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torrent_hash', sa.String(), nullable=True),
    sa.Column('source_title', sa.Text(), nullable=False),
    sa.Column('indexer', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('media_type', sa.Enum('movie', 'tv', name='mediatype', native_enum=False), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Enum('failed', 'bad_quality', 'wrong_media', 'user_reported', name='blocklistreason', native_enum=False), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocklist_added_at'), ['added_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocklist_source_title'), ['source_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocklist_torrent_hash'), ['torrent_hash'], unique=False)

    op.create_table('download_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('torrent_hash', sa.String(), nullable=True),
    sa.Column('event_type', sa.Enum('grabbed', 'import_started', 'imported', 'failed', name='downloadhistoryevent', native_enum=False), nullable=False),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('quality_json', sa.JSON(), nullable=True),
    sa.Column('indexer', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_history_torrent_hash'), ['torrent_hash'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    # encrypted_value is EncryptedStr (Fernet TypeDecorator); its DB-level impl
    # is String, so it is plain VARCHAR at rest with encryption applied in the
    # Python bind/result layer. Secret settings store ciphertext here.
    sa.Column('encrypted_value', sa.String(), nullable=True),
    # sa.false() renders the dialect boolean literal (0 on SQLite, false on
    # PostgreSQL); sa.text('0') would emit DEFAULT 0, rejected by PostgreSQL on a
    # BOOLEAN column. Postgres is a config swap, so the schema stays portable.
    sa.Column('is_secret', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=True)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    # sa.false(): portable boolean default (see settings.is_secret).
    sa.Column('initialized', sa.Boolean(), server_default=sa.false(), nullable=False),
    # The app API key is stored ONLY as its SHA-256 hex digest, never in plaintext
    # (a DB-backup leak of the raw bearer token would be an auth bypass, ADR-0005).
    # app_api_key is EncryptedStr (Fernet); its DB-level impl is String, so the
    # column is plain VARCHAR at rest with encryption applied in the Python layer.
    sa.Column('app_api_key', sa.String(), nullable=True),
    sa.Column('setup_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('setup_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    # Singleton: the install-state row is pinned to id=1, so a second insert can
    # never succeed (the app catches the violation and re-reads the one row).
    sa.CheckConstraint('id = 1', name='ck_system_settings_singleton')
    )
    op.create_table('tmdb_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('cache_type', sa.String(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tmdb_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tmdb_cache_cache_key'), ['cache_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_tmdb_cache_expires_at'), ['expires_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plex_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    # EncryptedStr is a Fernet TypeDecorator whose DB-level impl is String;
    # encryption happens in the Python bind/result layer, so the column is plain
    # VARCHAR at rest. Rendered as sa.String() to keep the migration decoupled
    # from application code (autogenerate emitted a bare unqualified reference).
    sa.Column('encrypted_plex_token', sa.String(), nullable=True),
    sa.Column('permissions', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_plex_id'), ['plex_id'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)

    op.create_table('media_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('movie', 'tv', name='mediatype', native_enum=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'searching', 'no_acceptable_release', 'downloading', 'completed', 'available', 'failed', name='requeststatus', native_enum=False), nullable=False),
    sa.Column('is_anime', sa.Boolean(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('library_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('library_removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_requests_tmdb_id'), ['tmdb_id'], unique=False)
        batch_op.create_index('ix_media_requests_tmdb_media', ['tmdb_id', 'media_type'], unique=False)
        # Partial UNIQUE index: dedup is enforced only across ACTIVE statuses, so a
        # second concurrent request for the same media raises IntegrityError (which
        # create_request resolves to the existing active request), while a fresh
        # request after the prior one reaches a terminal status is still allowed.
        # postgresql_where carries the SAME predicate as sqlite_where: without it
        # PostgreSQL ignores the sqlite-only clause and builds an UNCONDITIONAL
        # unique index, which would reject a valid re-request after the prior one
        # reached a terminal status. Both dialects must render the partial index.
        batch_op.create_index(
            'uq_media_requests_active',
            ['tmdb_id', 'media_type'],
            unique=True,
            sqlite_where=sa.text(
                "status IN ('pending', 'searching', 'no_acceptable_release', 'downloading')"
            ),
            postgresql_where=sa.text(
                "status IN ('pending', 'searching', 'no_acceptable_release', 'downloading')"
            ),
        )

    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_request_id', sa.Integer(), nullable=True),
    sa.Column('torrent_hash', sa.String(), nullable=False),
    # magnet_link is EncryptedStr (a download url can embed the Prowlarr api key);
    # its DB-level impl is String, so it is plain VARCHAR at rest with encryption
    # applied in the Python bind/result layer (ADR-0005).
    sa.Column('magnet_link', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('seed_ratio', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('target_seed_ratio', sa.Float(), server_default=sa.text('1'), nullable=False),
    sa.Column('media_type', sa.Enum('movie', 'tv', name='mediatype', native_enum=False), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('episodes_json', sa.JSON(), nullable=True),
    sa.Column('timeout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_reason', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('torrent_attempt', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('scored_releases_json', sa.JSON(), nullable=True),
    sa.Column('download_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['media_request_id'], ['media_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_downloads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_downloads_torrent_hash'), ['torrent_hash'], unique=True)
        # At most one active download per request (the DB backstop to the
        # app-level parallel-grab guard). Terminal statuses are excluded; the
        # predicate is supplied per-dialect so Postgres honours the partial index.
        batch_op.create_index(
            'uq_downloads_active_request',
            ['media_request_id'],
            unique=True,
            sqlite_where=sa.text(
                "media_request_id IS NOT NULL "
                "AND status NOT IN ('imported', 'failed', 'no_acceptable_release')"
            ),
            postgresql_where=sa.text(
                "media_request_id IS NOT NULL "
                "AND status NOT IN ('imported', 'failed', 'no_acceptable_release')"
            ),
        )

    op.create_table('season_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_request_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'searching', 'no_acceptable_release', 'downloading', 'completed', 'available', 'failed', name='requeststatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_request_id'], ['media_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('season_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_season_requests_media_request_id'), ['media_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_season_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_season_requests_status'))
        batch_op.drop_index(batch_op.f('ix_season_requests_media_request_id'))

    op.drop_table('season_requests')
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.drop_index('uq_downloads_active_request')
        batch_op.drop_index(batch_op.f('ix_downloads_torrent_hash'))
        batch_op.drop_index(batch_op.f('ix_downloads_status'))

    op.drop_table('downloads')
    with op.batch_alter_table('media_requests', schema=None) as batch_op:
        batch_op.drop_index('uq_media_requests_active')
        batch_op.drop_index('ix_media_requests_tmdb_media')
        batch_op.drop_index(batch_op.f('ix_media_requests_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_media_requests_status'))

    op.drop_table('media_requests')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action_type'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_plex_id'))

    op.drop_table('users')
    with op.batch_alter_table('tmdb_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tmdb_cache_expires_at'))
        batch_op.drop_index(batch_op.f('ix_tmdb_cache_cache_key'))

    op.drop_table('tmdb_cache')
    op.drop_table('system_settings')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))

    op.drop_table('settings')
    with op.batch_alter_table('download_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_history_torrent_hash'))

    op.drop_table('download_history')
    with op.batch_alter_table('blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocklist_torrent_hash'))
        batch_op.drop_index(batch_op.f('ix_blocklist_source_title'))
        batch_op.drop_index(batch_op.f('ix_blocklist_added_at'))

    op.drop_table('blocklist')
    # ### end Alembic commands ###
