"""add season_requests airing_refresh_checked_at rotation cursor

Revision ID: 3d28d05107aa
Revises: 4ea46e54d51c
Create Date: 2026-07-11 21:31:21.761683
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d28d05107aa"
down_revision: str | None = "4ea46e54d51c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # A timezone-aware TIMESTAMP, not a DATE (P2, issue #178 review round 2): a
    # date-granular rotation cursor collapses to id-ordering once every candidate
    # is stamped with the same day, starving high-id seasons until midnight on
    # installs with more eligible seasons than the per-cycle refresh budget.
    with op.batch_alter_table("season_requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("airing_refresh_checked_at", sa.DateTime(timezone=True), nullable=True)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("season_requests", schema=None) as batch_op:
        batch_op.drop_column("airing_refresh_checked_at")

    # ### end Alembic commands ###
