"""operability: log_events, library_path, keep_forever, evicted status

Four schema deltas for the operability beta (ADR-0012), shipped as one revision
since they are part of the same logical change (see
``docs/design/operability-beta-plan.md``):

1. New ``log_events`` table — the durable, LLM-diagnosable log trail. Populated
   only by the capture pipeline's async drain task, never the synchronous
   logging handler itself (see ``models.LogEvent``).
2. ``media_requests.library_path`` — the final placed path the importer wrote a
   movie into, captured (never reconstructed) at import/availability time so
   disk-pressure eviction knows exactly what to ``fs.delete()``.
3. ``media_requests.keep_forever`` — the operator "never evict this" pin.
4. ``season_requests.library_path`` — the per-season mirror of (2), for TV.

``RequestStatus.evicted`` needs NO migration of its own: ``media_requests.status``
/ ``season_requests.status`` are plain VARCHAR columns (SQLAlchemy 2.0's
``native_enum=False`` creates no CHECK constraint — precedent ``41d427bd38e6``),
and ``uq_media_requests_active``'s predicate is UNCHANGED: ``evicted`` is
deliberately excluded from it, same as the existing settled ``available`` /
``failed`` statuses, so a re-request after an eviction is never blocked by the
old (now off-disk) row. See ``RequestStatus.evicted``'s docstring in
``models.py`` and the ``uq_media_requests_active`` index comment.

Revision ID: 6c7fca1436d8
Revises: d3a7077fdbcc
Create Date: 2026-07-01 03:12:25.640103
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c7fca1436d8"
down_revision: str | None = "d3a7077fdbcc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("level", sa.String(), nullable=False),
        sa.Column("logger", sa.String(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("context_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("log_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_log_events_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("media_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("library_path", sa.String(), nullable=True))
        # sa.false() (not sa.text("0")) renders the dialect's boolean literal —
        # portable to PostgreSQL, which rejects DEFAULT 0 on a BOOLEAN column.
        batch_op.add_column(
            sa.Column("keep_forever", sa.Boolean(), server_default=sa.false(), nullable=False)
        )

    with op.batch_alter_table("season_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("library_path", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("season_requests", schema=None) as batch_op:
        batch_op.drop_column("library_path")

    with op.batch_alter_table("media_requests", schema=None) as batch_op:
        batch_op.drop_column("keep_forever")
        batch_op.drop_column("library_path")

    with op.batch_alter_table("log_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_log_events_created_at"))

    op.drop_table("log_events")
    # ### end Alembic commands ###
