"""lease download cleanup workers

Revision ID: b208fe0e4f7a
Revises: bfa867fe6d6f
Create Date: 2026-07-29 13:51:55.668923
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b208fe0e4f7a"
down_revision: str | None = "bfa867fe6d6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("download_add_intents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cleanup_lease_token", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("cleanup_lease_acquired_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("download_add_intents", schema=None) as batch_op:
        batch_op.drop_column("cleanup_lease_acquired_at")
        batch_op.drop_column("cleanup_lease_token")

    # ### end Alembic commands ###
