"""persist synthetic late cleanup identity

Revision ID: bfa867fe6d6f
Revises: c7967dc972e4
Create Date: 2026-07-29 11:33:43.856905
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfa867fe6d6f"
down_revision: str | None = "c7967dc972e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("download_add_intents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cleanup_torrent_hash", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("cleanup_category", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # c796 cannot recover synthetic rows because it lacks their real client hash and
    # original category token. Delete them before dropping those fields. A colliding
    # real-hash reservation remains untouched; a no-collision synthetic incident is
    # intentionally retired rather than downgraded into an unremovable fake hash.
    op.execute("DELETE FROM download_add_intents WHERE cleanup_torrent_hash IS NOT NULL")
    with op.batch_alter_table("download_add_intents", schema=None) as batch_op:
        batch_op.drop_column("cleanup_category")
        batch_op.drop_column("cleanup_torrent_hash")
