"""add download release_title column

Revision ID: bfaa63130ee7
Revises: 26d44ca5f471
Create Date: 2026-07-07 11:45:17.114301
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfaa63130ee7"
down_revision: str | None = "26d44ca5f471"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("downloads", schema=None) as batch_op:
        batch_op.add_column(sa.Column("release_title", sa.String(), nullable=True))

    # ### end Alembic commands ###

    # Backfill: best-effort recover the release title for EXISTING rows from the
    # append-only download_history log (the same source_title grab_service has
    # always written at grab time) -- so an operator upgrading mid-download still
    # sees a human release name in the queue instead of a hole this migration
    # otherwise leaves. The newest source_title per hash wins (a hash can be
    # re-grabbed/resurrected across a terminal-row reuse, and the LATEST grab's
    # title is the one that owns the row's CURRENT download).
    op.execute(
        "UPDATE downloads SET release_title = ("
        "SELECT dh.source_title FROM download_history dh "
        "WHERE dh.torrent_hash = downloads.torrent_hash "
        "AND dh.source_title IS NOT NULL "
        "ORDER BY dh.id DESC LIMIT 1"
        ")"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("downloads", schema=None) as batch_op:
        batch_op.drop_column("release_title")

    # ### end Alembic commands ###
