"""add blocklist tmdb_id/media_type index

Revision ID: c86212dad733
Revises: 5e8b1a4f2c9d
Create Date: 2026-07-07 21:52:45.120787
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c86212dad733"
down_revision: str | None = "5e8b1a4f2c9d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blocklist", schema=None) as batch_op:
        batch_op.create_index("ix_blocklist_tmdb_media", ["tmdb_id", "media_type"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blocklist", schema=None) as batch_op:
        batch_op.drop_index("ix_blocklist_tmdb_media")

    # ### end Alembic commands ###
