"""add request poster/backdrop art columns

Revision ID: f679b4c17194
Revises: 309cbf9239c3
Create Date: 2026-06-30 13:34:53.678863
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f679b4c17194"
down_revision: str | None = "309cbf9239c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("poster_url", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("backdrop_url", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media_requests", schema=None) as batch_op:
        batch_op.drop_column("backdrop_url")
        batch_op.drop_column("poster_url")

    # ### end Alembic commands ###
